
# File: obsidianwall-core/ObsidianWall_SIaC/modules/netbird-vpn-server/.github/workflows/ci-security.yml

# Purpose: Local module build-time security validation (tfsec + Checkov + TFLint)
# This GitHub Actions workflow runs static security scans on Terraform code
# using TFLint, tfsec, and Checkov. It is triggered on pushes and pull requests


name: Static IaC Security Scan (netbird-vpn-server)

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  security-scan:
    name: Security + Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  ObsidianWall_SIaC/modules/netbird-vpn-server  # adjust per module if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ObsidianWall_SIaC/modules/netbird-vpn-server

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ObsidianWall_SIaC/modules/netbird-vpn-server
