
# File: obsidianwall-core/ObsidianWall_SIaC/modules/netbird-vpn-server/.github/workflows/ci-security.yml

# Purpose: Local module build-time security validation (tfsec + Checkov + TFLint)
# This GitHub Actions workflow runs static security scans on Terraform code
# using TFLint, tfsec, and Checkov. It is triggered on pushes and pull requests



name: Static IaC Security Scan Reusable Module CI (netbird-vpn-server)

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  module-ci:
    uses: ./.github/workflows/module-ci-template.yml
    with:
      working-directory: ObsidianWall_SIaC/modules/netbird-vpn-server  # adjust per module if needed

