
# File: obsidianwall-core/ObsidianWall_SIaC/modules/azure-vm/.github/workflows/ci-security.yml

# Purpose: Local module build-time security validation (tfsec + Checkov + TFLint)

# Note: This workflow is triggered on changes to Terraform files (.tf, .tfvars) in the repository.





name: Static IaC Security Scan Reusable Module CI (azure-vm)

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  module-ci:
    uses: obsidianwall-core/.github/workflows/module-ci-template.yml@v1
    with:
      working-directory: ObsidianWall_SIaC/modules/azure-vm  # adjust per module if needed
