
# File: obsidianwall-core/ObsidianWall_SIaC/modules/aws_ec2/.github/workflows/ci-security.yml

# Purpose: Local module build-time security validation (tfsec + Checkov + TFLint)

# Note: This workflow is triggered on changes to Terraform files (.tf, .tfvars) in the module directory.


name: Static IaC Security Scan (aws-ec2)

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  security-scan:
    name: Security + Linting
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  ObsidianWall_SIaC/modules/aws-ec2  # adjust per module if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1
        with:
          working_directory:  ObsidianWall_SIaC/modules/aws-ec2

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory:  ObsidianWall_SIaC/modules/aws-ec2