
# File: obsidianwall-core/ObsidianWall_SIaC/modules/aws_ec2/.github/workflows/ci-security.yml

# Purpose: Local module build-time security validation (tfsec + Checkov + TFLint)

# Note: This workflow is triggered on changes to Terraform files (.tf, .tfvars) in the module directory.





name: Static IaC Security Scan Reusable Module CI (aws-ec2)

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  module-ci:
    uses: obsidianwall-core/.github/workflows/module-ci-template.yml@v1
    with:
      working-directory: ObsidianWall_SIaC/modules/aws-ec2   # adjust per module if needed


