
# File: ObsidianWall_SIaC/modules/test-module/.github/workflows/ci-security.yml


name: Module CI - test-module

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  call-module-template:
    uses: obsidianwall-core/.github/workflows/module-ci-template.yml@v1
    with:
      working-directory: ObsidianWall_SIaC/modules/test-module  # adjust per module if needed

