
# File: obsidianwall-core/ObsidianWall_SIaC/modules/ndr-azure-vm/.github/workflows/ci-security.yml

# Description: GitHub Actions workflow for static security scanning of Terraform code
# Purpose: Local module build-time security validation (tfsec + Checkov + TFLint)
# Note: This workflow is designed to be reusable for different modules by specifying the working directory



name: Static IaC Security Scan Reusable Module CI (ndr-azure-vm)

on:
  push:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  module-ci:
    uses: ./.github/workflows/module-ci-template.yml
    with:
      working-directory: ObsidianWall_SIaC/modules/ndr-azure-vm  # adjust per module if needed
