
# File: obsidianwall-core/.github/workflows/cd-dev.yml



# Description: Continuous Deployment (CD) workflow for deploying the development infrastructure using Terraform.
# 🚀 CD: Auto-deploy infrastructure to dev environment
# Runs on push to main or upon tag release (if configured)
# Useful for testing ObsidianWall SIaC end-to-end in dev



name: CD - Deploy Dev Infra

# 🛡️ Permissions: Define what the job can access
permissions:
  contents: read               # required for actions/checkout
  pull-requests: write         # only if writing comments to PRs
  # id-token: write            # uncomment for OIDC auth (e.g., cloud deployments)
  # packages: read             # needed if pulling from GHCR or private packages
  # issues: write              # for workflows that comment on issues
  # actions: read              # for composite actions or reuse
  # security-events: write     # for uploading SARIF to GitHub Security tab
  # deployments: write         # if performing GitHub deployments
  # statuses: write            # if setting commit status (e.g., from tests or scans)

on:
  push:
    branches: [ main ]
    paths:
      - 'ObsidianWall_SIaC/environments/dev/**.tf'
      - 'ObsidianWall_SIaC/environments/dev/**.tfvars'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest


    defaults:
      run:
        working-directory: ObsidianWall_SIaC/environments/dev/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@vc65cd883420fd2eb864698a825fc4162dd94482c  # v4, pinned version tag for security & stability

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
