# File: obsidianwall-core/.github/workflows/ci-core-plan.yml


# This GitHub Actions workflow is designed to run Terraform plan commands
# This workflow is triggered on pushes and pull requests to the dev environment directory.


name: CI - Core Infra Plan

# 🛡️ Permissions: Define what the job can access
permissions:
  contents: read               # required for actions/checkout
  pull-requests: write         # only if writing comments to PRs
  # id-token: write            # uncomment for OIDC auth (e.g., cloud deployments)
  # packages: read             # needed if pulling from GHCR or private packages
  # issues: write              # for workflows that comment on issues
  # actions: read              # for composite actions or reuse
  # security-events: write     # for uploading SARIF to GitHub Security tab
  # deployments: write         # if performing GitHub deployments
  # statuses: write            # if setting commit status (e.g., from tests or scans)

on:
  push:
    paths:
      - 'ObsidianWall_SIaC/environments/dev/**.tf'
      - 'ObsidianWall_SIaC/environments/dev/**.tfvars'
  pull_request:
    paths:
      - 'ObsidianWall_SIaC/environments/dev/**.tfvars'
      - 'ObsidianWall_SIaC/environments/dev/**.tf'

jobs:
  plan-core:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ObsidianWall_SIaC/environments/dev/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4 #(v3), v44, using specific commit SHA for stability

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
