# File: .github/workflows/ci-core-plan.yml

# This GitHub Actions workflow is designed to run Terraform plan commands
# This workflow is triggered on pushes and pull requests to the dev environment directory.


name: CI - Core Infra Plan

on:
  push:
    paths:
      - 'ObsidianWall_SIaC/environments/dev/**'
  pull_request:
    paths:
      - 'ObsidianWall_SIaC/environments/dev/**'

jobs:
  plan-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ObsidianWall_SIaC/environments/dev/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
