
# File: obsidianwall-core/.github/workflows/ci-security.yml

# Project: ObsidianWall CI/CD Security Workflow
# Description: This workflow runs static security scans on Terraform modules
# 🔍 Static analysis with tfsec + checkov on modules
# Runs dual scan engines on all modules in matrix:
# - tfsec (Terraform-specific vulnerabilities)
# - checkov (broader IaC misconfigurations)




name: Static Security Scan (tfsec, checkov, tflint)

on:
  push:
    paths:
      - 'ObsidianWall_SIaC/modules/**'
  pull_request:
    paths:
      - 'ObsidianWall_SIaC/modules/**'

jobs:
  security-scan:
    name: Module Security Scanning
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - ObsidianWall_SIaC/modules/aws-ec2
          - ObsidianWall_SIaC/modules/azure-vm
          - ObsidianWall_SIaC/modules/azure-storage
          - ObsidianWall_SIaC/modules/ndr-azure-vm
          - ObsidianWall_SIaC/modules/ndr-aws-ec2
          - ObsidianWall_SIaC/modules/netbird-vpn-server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Register TFLint Matcher
        run: echo "::add-matcher::.github/matchers/tflint.json"

      - name: Run TFLint (with annotations)
        run: |
          cd ${{ matrix.module }}
          tflint --init
          tflint --format=compact

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1
        with:
          working_directory: ${{ matrix.module }}

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ matrix.module }}
