
# 🔍 Static analysis with tfsec + checkov on modules
# Runs dual scan engines on all modules in matrix:
# - tfsec (Terraform-specific vulnerabilities)
# - checkov (broader IaC misconfigurations)




name: Static Security Scan (tfsec & checkov)

on:
  push:
    paths:
      - 'ObsidianWall_SIaC/modules/**'
  pull_request:
    paths:
      - 'ObsidianWall_SIaC/modules/**'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - ObsidianWall_SIaC/modules/netbird-ec2
          - ObsidianWall_SIaC/modules/netbird-azure-vm
          - ObsidianWall_SIaC/modules/ndr-azure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1
        with:
          working_directory: ${{ matrix.module }}

      - name: Run checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ matrix.module }}
