
# File: obsidianwall-core/.github/workflows/ci-security.yml


# Project: ObsidianWall CI/CD Security Workflow
# Description: This workflow runs static security scans on Terraform modules
# 🔍 Static analysis with (tfsec + Checkov + TFLint)on modules
# Runs dual scan engines on all modules in matrix:
# - tfsec (Terraform-specific vulnerabilities)
# - checkov (broader IaC misconfigurations)




name: Static Security Scan (tfsec, checkov)

on:
  push:
    paths:
      - 'ObsidianWall_SIaC/modules/**'
  pull_request:
    paths:
      - 'ObsidianWall_SIaC/modules/**'

jobs:
  security-scan:
    name: Module Security Scanning
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - ObsidianWall_SIaC/modules/aws-ec2
          - ObsidianWall_SIaC/modules/azure-vm
          - ObsidianWall_SIaC/modules/azure-storage
          - ObsidianWall_SIaC/modules/aws-s3
          - ObsidianWall_SIaC/modules/ndr-azure-vm
          - ObsidianWall_SIaC/modules/ndr-aws-ec2
          - ObsidianWall_SIaC/modules/netbird-vpn-server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ matrix.module }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # ✅ prevents rate-limiting


      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.2170.0
        with:
          directory: ${{ matrix.module }}