
# File: .github/workflows/lint-permissions.yml
# 👀 CI Security Guardrail: Detect workflows with overly permissive permissions

name: Lint Workflow Permissions

# 🛡️ Permissions: Define what the job can access
permissions:
  contents: read               # required for actions/checkout
  pull-requests: write         # only if writing comments to PRs
  # id-token: write            # uncomment for OIDC auth (e.g., cloud deployments)
  # packages: read             # needed if pulling from GHCR or private packages
  # issues: write              # for workflows that comment on issues
  # actions: read              # for composite actions or reuse
  # security-events: write     # for uploading SARIF to GitHub Security tab
  # deployments: write         # if performing GitHub deployments
  # statuses: write            # if setting commit status (e.g., from tests or scans)

on:
  pull_request:
    paths:
      - '.github/workflows/**.yml'

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    name: Detect Dangerous Workflow Permissions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Scan for permission escalation
        run: |
          echo "Scanning GitHub workflows for elevated permissions..."
          grep -r 'permissions:' .github/workflows | grep -E 'write-all|id-token: write|deployments: write|security-events: write' && \
            echo '::error ::⚠️ Detected overly permissive permissions! Please review.' && exit 1 || \
            echo '✅ No overly permissive workflows detected.'

