
# File: obsidianwall-core/.github/workflows/module-ci-template.yml
# This workflow is a reusable module CI template for validating and securing Terraform modules.
# It includes steps for Terraform initialization, formatting, validation, linting with TFLint, and security checks.
# # Purpose: Local module build-time security validation (tfsec + Checkov + tfint).



name: Reusable Module CI Template

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  module-ci:
    name: Validate & Secure Module 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    permissions:
      contents: read
      id-token: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TFSEC_GITHUB_TOKEN: ${{ secrets.TFSEC_GITHUB_TOKEN }}
      CHECKOV_GITHUB_TOKEN: ${{ secrets.CHECKOV_GITHUB_TOKEN }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.1.0
        with:
          tflint_version: latest

      - name: Run TFLint
        run: |
          tflint --init
          tflint --format=compact

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ inputs.working-directory }} 

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.2170.0
        with:
          directory: ${{ inputs.working-directory }}
