
# File: .github/workflows/module-ci-template.yml
# This workflow is a reusable module CI template for validating and securing Terraform modules.



name: Reusable Module CI Template

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  module-ci:
    name: Validate & Secure Module
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4.1.0
        with:
          tflint_version: latest

      - name: Run TFLint
        run: |
          tflint --init
          tflint --format=compact

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ inputs.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12.2170.0
        with:
          directory: ${{ inputs.working-directory }}
