
# File: obsidianwall-core/.github/workflows/validate-policy-azure.yml

# This GitHub Actions workflow validates Azure Policy compliance for the ObsidianWall project.
# ✅ Azure Policy Validator for ObsidianWall
# - Validates deployed Terraform templates using Azure Policy
# - Uses az CLI to fetch policy compliance results
# - Optional: Runs terrascan for IaC-level static analysis


name: Validate Azure Policies

# 🛡️ Permissions: Define what the job can access
permissions:
  contents: read               # required for actions/checkout
  pull-requests: write         # only if writing comments to PRs
  # id-token: write            # uncomment for OIDC auth (e.g., cloud deployments)
  # packages: read             # needed if pulling from GHCR or private packages
  # issues: write              # for workflows that comment on issues
  # actions: read              # for composite actions or reuse
  # security-events: write     # for uploading SARIF to GitHub Security tab
  # deployments: write         # if performing GitHub deployments
  # statuses: write            # if setting commit status (e.g., from tests or scans)

on:
  pull_request:
    paths:
      - 'ObsidianWall_SIaC/modules/**.tf'
      - 'ObsidianWall_SIaC/modules/**.tfvars'
  push:
    branches: [main]
    paths:
      - 'ObsidianWall_SIaC/modules/**.tf'
      - 'ObsidianWall_SIaC/modules/**.tfvars'

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  RESOURCE_GROUP: obsidianwall-validation-rg # Change to your actual validation RG
  POLICY_SCOPE: /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }} # or narrower scope

jobs:
  azure-policy-validation:
    name: Azure Policy Compliance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@4                               ## using commit SHA for stability
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: List assigned policies in scope
        run: |
          echo "Fetching policy assignments for scope: $POLICY_SCOPE"
          az policy assignment list --scope $POLICY_SCOPE --output table

      - name: Show current policy compliance state
        run: |
          echo "Checking compliance..."
          az policy state list --query "[?complianceState=='NonCompliant']" --output table

      - name: (Optional) Run Terrascan on modules
        uses: accurics/terrascan-action@4                                          # using commit SHA for stability
        with:
          iac_type: terraform
          iac_version: v14
          policy_type: azure
          iac_dir: ObsidianWall_SIaC/modules
