# File: obsidianwall-core/.github/workflows/validate-terraform.yml

# Description: Validate Terraform modules in the ObsidianWall_SIaC repository
# This GitHub Actions workflow validates Terraform modules in the ObsidianWall_SIaC repository.
# ✅ Format, init, and plan Terraform modules on push/PR
# Ensures Terraform is correctly formatted and runs a speculative plan
# Requires TF_API_TOKEN for Terraform Cloud (if using remote backend)



name: Validate Terraform

on:
  pull_request:
    paths:
      - 'ObsidianWall_SIaC/modules/**'
  push:
    branches: [main]
    paths:
      - 'ObsidianWall_SIaC/modules/**'

jobs:
  terraform-validate:
    name: Terraform Format, Validate, Lint, and Plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - ObsidianWall_SIaC/modules/aws-ec2
          - ObsidianWall_SIaC/modules/azure-vm
          - ObsidianWall_SIaC/modules/azure-storage
          - ObsidianWall_SIaC/modules/aws-s3
          - ObsidianWall_SIaC/modules/ndr-azure-vm
          - ObsidianWall_SIaC/modules/ndr-aws-ec2
          - ObsidianWall_SIaC/modules/netbird-vpn-server

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.module }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Register TFLint Matcher
        run: echo "::add-matcher::.github/matchers/tflint.json"

      - name: Run TFLint
        run: |
          tflint --init
          tflint --format=compact  

      - name: Terraform Plan (Speculative)
        run: terraform plan -input=false
