
#file: obsidianwall-core/.github/workflows/validate-policy-open.yml

# This workflow validates Open policies using OPA and Conftest.




name: Validate Open Policies

# 🛡️ Permissions: Define what the job can access
permissions:
  contents: read               # required for actions/checkout
  pull-requests: write         # only if writing comments to PRs
  # id-token: write            # uncomment for OIDC auth (e.g., cloud deployments)
  # packages: read             # needed if pulling from GHCR or private packages
  # issues: write              # for workflows that comment on issues
  # actions: read              # for composite actions or reuse
  # security-events: write     # for uploading SARIF to GitHub Security tab
  # deployments: write         # if performing GitHub deployments
  # statuses: write            # if setting commit status (e.g., from tests or scans)

on:
  push:
    paths:
      - 'policies/open-source/**'
      
  pull_request:
    paths:
      - 'policies/open-source/**'

jobs:
  opa-validate:
    name: Run OPA/Conftest Policies
    runs-on: ubuntu-latest

   
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
          tar -xzf conftest_0.45.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Policy Checks
        run: |
          conftest test ObsidianWall_SIaC/modules/aws-ec2/main.tf
