# File: obsidianwall-core/.github/workflows/validate-pr.yml

# Description: This GitHub Actions workflow validates pull request titles and descriptions to ensure they follow a meaningful format.
# 🚦 Validate pull requests for formatting and merge hygiene
# Runs only on PRs to ensure code quality and structural integrity




name: Validate Pull Request Title and Description

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR title is meaningful
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
