# File: obsidianwall-core/.github/workflows/validate-pr.yml

# Description: This GitHub Actions workflow validates pull request titles and descriptions to ensure they follow a meaningful format.
# 🚦 Validate pull requests for formatting and merge hygiene
# Runs only on PRs to ensure code quality and structural integrity




name: Validate Pull Request Title and Description

# 🛡️ Permissions: Define what the job can access
permissions:
  contents: read               # required for actions/checkout
  pull-requests: write         # only if writing comments to PRs
  # id-token: write            # uncomment for OIDC auth (e.g., cloud deployments)
  # packages: read             # needed if pulling from GHCR or private packages
  # issues: write              # for workflows that comment on issues
  # actions: read              # for composite actions or reuse
  # security-events: write     # for uploading SARIF to GitHub Security tab
  # deployments: write         # if performing GitHub deployments
  # statuses: write            # if setting commit status (e.g., from tests or scans)


on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    

    steps:
      - name: Ensure PR title is meaningful
        uses: amannn/action-semantic-pull-request@4                             # using specific commit SHA for stability
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
