
# File: .github/workflows/validate-ci-health.yml
# This workflow validates the CI coverage for the ObsidianWall_SIaC module.
# Purpose: Run weekly + on PR to check for CI coverage gaps



name: Validate CI Coverage

on:
  schedule:
    - cron: '0 4 * * 1'  # every Monday at 4 AM UTC
  pull_request:
    paths:
      - 'ObsidianWall_SIaC/modules/**'

jobs:
  check-ci-health:
    name: Check CI Module Coverage
    runs-on: ubuntu-latest

    # 🛡️ Permissions: Define what the job can access
    permissions:
      contents: read               # required for actions/checkout
      pull-requests: write         # only if writing comments to PRs
      
      # id-token: write            # uncomment for OIDC auth (e.g., cloud deployments)
      # packages: read             # needed if pulling from GHCR or private packages
      # issues: write              # for workflows that comment on issues
      # actions: read              # for composite actions or reuse
      # security-events: write     # for uploading SARIF to GitHub Security tab
      # deployments: write         # if performing GitHub deployments
      # statuses: write            # if setting commit status (e.g., from tests or scans)


    defaults:
      run:
        shell: bash
        working-directory: obsidianwall-core/ObsidianWall_SIaC/scripts

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run CI Health Validator
        run: ./validate-ci-health.sh
